### ISSUE TITLE
Proposal – adding ripemd160

### ISSUE THREAD

**Issue by sac001** [ultimateanu/hashdir#14]
Hi,

I was looking for a special hashing utility and found yours, which is pretty awesome and does what I like to archive. However, for a special use case (a transaction, which must include a hash) I would like to ask if you can include for users, of your fine software, living in for example Europe, to include ripemd160. I ask, because security wise I have no need for md5 or sha1 and sha256 output is too long, compared to also secure ripemd160, which is also used, for example, in the Bitcoin protocol.

Best regards
Stefan

**Comment by sac001** [comment]
Thanks for reading and adding the enhancement label.

**Comment by ultimateanu** [comment]
Ripemd-160 is added in v1.1.0.

It can be used using the `-a` flag:
`hashdir -a ripemd160 --save ~/Desktop/hello.txt`

If you need to check the hash file later you can do:
`hashdir check ~/Desktop/hello.txt.1.ripemd160.txt`
Note that this uses the filename to determine the hash algorithm. This is needed because both ripemd-160 and sha1 are 160 bits.

If the hashfile is renamed or doesn't have the hash algorithm name you can specify the type during checking:
`hashdir check -a ripemd160 ~/Desktop/hello.txt.hash.txt`

**Comment by sac001** [comment]
Awesome! Thank you so much! I very much appreciate that you added RIPEMD-160.

Best regards
Stefan
